.github: bump Go version to 1.17
We need to update Go version to 1.17, to fix the following build error,
which we see with golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2.

```
Error: ../../../go/pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/transport.go:417:45:
undefined: os.ErrDeadlineExceeded
note: module requires Go 1.17
```